default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  primary:
    <<: *default
    database: athenai_development

  cable:
    <<: *default
    database: athenai_development_cable
    migrations_paths: db/cable_migrate


test:
  <<: *default
  database: athenai_test
  user: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>


production:
  primary: &primary_production
    <<: *default
    database: athenai_production
  queue:
    <<: *primary_production
    database: athenai_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: athenai_production_cable
    migrations_paths: db/cable_migrate
